<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>2.4.1</AssemblyVersion>
    <FileVersion>2.4.1</FileVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0 " />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0 " />
    <PackageReference Include="Jellyfin.Data" Version="12.1.0 " />
    <PackageReference Include="Jellyfin.Common" Version="12.1.0 " />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Resources\*.json" />
    <EmbeddedResource Include="thumb.png" />
  </ItemGroup>

</Project>